country=("Francia","Inglaterra","España","Alemania","Australia")
print(country)
print()
country=input("Inserte uno de los países de arriba: ")
print(country, "has index number: ", country.index(country))